modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (26 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="toolkit" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Tool Kit" #mandatory
displayURL="http://example.com/" #optional
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Sunekaer" #optional
description='''
This mod adds bunch of useful commands
'''
[[dependencies.toolkit]]
modId="forge"
mandatory=true
versionRange="[30.0.7,)"
ordering="NONE"
side="BOTH"

[[dependencies.toolkit]]
modId="minecraft"
mandatory=true
versionRange="[1.15.1]"
ordering="NONE"
side="BOTH"